default_positions:
  "0":   -0.23
  "1":   -0.03
  "2":   0.0
  "3":   -0.32
  "4":   0.25
  "5":   -0.30
  "6":   0.23
  "7":   0.02
  "8":   0.0
  "9":   0.32
  "10":  -0.25
  "11":  0.30
  "12":  0.0
  "13":  0.0
  "14":  0.0
  "15":  0.0
  "16":  -1.0
  "17":  0.0
  "18":  0.0
  "19":  0.0
  "20":  0.0
  "21":  1.0