default_positions:
  "0":   -0.25
  "1":   -0.03
  "2":   -0.01
  "3":   -0.5
  "4":   0.29
  "5":   -0.27
  "6":   0.25
  "7":   0.03
  "8":   0.01
  "9":   0.5
  "10":  -0.27
  "11":  0.29
  "12":  0.0
  "13":  0.0
  "14":  0.0
  "15":  0.0
  "16":  -1.0
  "17":  0.0
  "18":  0.0
  "19":  0.0
  "20":  0.0
  "21":  1.0