joint_limits:
  "0":
    min_position: -2.09
    max_position: 0.78
    max_velocity: 1.0
    max_effort: 50.0
  "1":
    min_position: -2.18
    max_position: 0.44
    max_velocity: 1.0
    max_effort: 40.0
  "2":
    min_position: -1.38
    max_position: 1.19
    max_velocity: 1.0
    max_effort: 40.0
  "3":
    min_position: -2.04
    max_position: 0.0
    max_velocity: 1.0
    max_effort: 50.0
  "4":
    min_position: -0.91
    max_position: 1.13
    max_velocity: 1.0
    max_effort: 30.0
  "5":
    min_position: -1.11
    max_position: 1.28
    max_velocity: 1.0
    max_effort: 30.0
  "6":
    min_position: -0.79
    max_position: 2.09
    max_velocity: 1.0
    max_effort: 50.0
  "7":
    min_position: -0.44
    max_position: 2.17
    max_velocity: 1.0
    max_effort: 40.0
  "8":
    min_position: -1.32
    max_position: 1.26
    max_velocity: 2.0
    max_effort: 40.0
  "9":
    min_position: 0.0
    max_position: 2.04
    max_velocity: 1.0
    max_effort: 50.0
  "10":
    min_position: -1.04
    max_position: 1.34
    max_velocity: 1.0
    max_effort: 30.0
  "11":
    min_position: -1.33
    max_position: 1.17
    max_velocity: 1.0
    max_effort: 30.0
  "12":
    min_position: -1.0
    max_position: 1.0
    max_velocity: 1.0
    max_effort: 30.0
  "13":
    min_position: -1.5
    max_position: 0.7
    max_velocity: 1.0
    max_effort: 30.0
  "14":
    min_position: -1.5
    max_position: 0.0
    max_velocity: 1.0
    max_effort: 30.0
  "15":
    min_position: -1.0
    max_position: 1.8
    max_velocity: 1.0
    max_effort: 30.0
  "16":
    min_position: -2.0
    max_position: 0.0
    max_velocity: 1.0
    max_effort: 30.0
  "17":
    min_position: -1.1
    max_position: 1.1
    max_velocity: 1.0
    max_effort: 30.0
  "18":
    min_position: -0.5
    max_position: 1.5
    max_velocity: 1.0
    max_effort: 30.0
  "19":
    min_position: 0.0
    max_position: 1.5
    max_velocity: 1.0
    max_effort: 30.0
  "20":
    min_position: -1.8
    max_position: 1.0
    max_velocity: 1.0
    max_effort: 30.0
  "21":
    min_position: 0.0
    max_position: 2.0
    max_velocity: 1.0
    max_effort: 30.0