joint_pds:
  "0":
    kp: 50.0
    kd: 10.0
  "1":
    kp: 50.0
    kd: 10.0
  "2":
    kp: 50.0
    kd: 10.0
  "3":
    kp: 50.0
    kd: 10.0
  "4":
    kp: 10.0
    kd: 10.0
  "5":
    kp: 10.0
    kd: 10.0
  "6":
    kp: 50.0
    kd: 10.0
  "7":
    kp: 50.0
    kd: 10.0
  "8":
    kp: 50.0
    kd: 10.0
  "9":
    kp: 50.0
    kd: 10.0
  "10":
    kp: 10.0
    kd: 10.0
  "11":
    kp: 10.0
    kd: 10.0
  "12":
    kp: 100.0
    kd: 10.0
  "13":
    kp: 5.0
    kd: 5.0
  "14":
    kp: 5.0
    kd: 5.0
  "15":
    kp: 2.0
    kd: 5.0
  "16":
    kp: 5.0
    kd: 5.0
  "17":
    kp: 0.0
    kd: 5.0
  "18":
    kp: 5.0
    kd: 5.0
  "19":
    kp: 5.0
    kd: 5.0
  "20":
    kp: 2.0
    kd: 5.0
  "21":
    kp: 5.0
    kd: 5.0
