joint_pds:
  "0":
    kp: 50.0
    kd: 3.0
  "1":
    kp: 50.0
    kd: 3.0
  "2":
    kp: 50.0
    kd: 3.0
  "3":
    kp: 50.0
    kd: 3.0
  "4":
    kp: 50.0
    kd: 3.0
  "5":
    kp: 50.0
    kd: 3.0
  "6":
    kp: 50.0
    kd: 3.0
  "7":
    kp: 50.0
    kd: 3.0
  "8":
    kp: 50.0
    kd: 3.0
  "9":
    kp: 50.0
    kd: 3.0
